name: "weekly sanity test"
on:
  schedule:
    - cron:  '30 20 * * 1'

jobs:
  sanity:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [8, 11, 17]
        impl: [temurin]
        buildlist: [openjdk, system, functional]
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
    - uses: actions/setup-java@19eeec562b37d29a1ad055b7de9c280bd0906d8d # v3.7.0
      with:
        java-version: ${{ matrix.version }}
        distribution: ${{ matrix.impl }}
    - name: AQA
      uses: ./
      with: 
        version: ${{ matrix.version }}
        jdksource: 'install-jdk'
        build_list: ${{ matrix.buildlist}}
        target: '_sanity.regular'
