name: "weekly sanity test"
on:
  schedule:
    - cron:  '30 20 * * 1'

jobs:
  sanity:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [8, 11, 17]
        impl: [temurin]
        buildlist: [openjdk, system, functional]
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
    - uses: actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc # v3.6.0
      with:
        java-version: ${{ matrix.version }}
        distribution: ${{ matrix.impl }}
    - name: AQA
      uses: ./
      with: 
        version: ${{ matrix.version }}
        jdksource: 'install-jdk'
        build_list: ${{ matrix.buildlist}}
        target: '_sanity.regular'
